Settings:
  Prefix: "&f[ &6DSE &f] "

  # 치명타 확률이 100%를 넘어가는경우 넘어간 수치의 치명타 확률을 또 계산하여 데미지에 적용시킵니다.
  # [ 예시 ]
  # 치확 : 120%
  # 치뎀 : 2
  # 데미지 : 10
  # 최종 데미지 = 20 or 40
  useOverCriticalChance: false

  # 해당 수치를 기반으로 기본 치명타 데미지를 계산합니다.
  # 해당 수치를 수정하시면 데미지에 큰 영향을 미칠 수 있습니다.
  # 꼭 데미지 계산을 하신뒤에 수정하시기 바랍니다.
  # 기본값으로 설정된 수치는 2배입니다.
  defaultCriticalAmount: 2

  # 해당 수치의 틱마다 체력, 이동속도 체크 및 적용 간격을 설정합니다.
  # 기본값으로 설정된 수치는 2틱 입니다.
  attributeCheckInterval: 2